---
- hosts: managed
  vars:
    mysql_root_password: ytq1ZsB2RaL41kJOS
    line_for_ftp: "in.proftpd : 10.1.0.0/255.255.255.0 : allow"
  tasks:
  - name: Install epel repo
    yum: name=epel-release state=latest

  - name: Install php repo
    yum: name=https://mirror.webtatic.com/yum/el7/webtatic-release.rpm state=present

  - name: Install Proftpd
    yum: name=proftpd state=latest

  - name: Install Apache
    yum: name=httpd state=latest

  - name: Install GeoIP
    yum: name=mod_geoip state=latest

  - name: Install Nginx
    yum: name=nginx state=latest

  - name: Install php 5.6
    yum: name=php56w state=latest

  - name: Install php gd library
    yum: name=php56w-gd state=latest

  - name: Install MariaDB Server
    yum: name=mariadb-server state=latest

  - name: Install MariaDB dev
    yum: name=mariadb-devel state=latest

  - name: Install Python dev
    yum: name=python-devel state=latest

  - name: Install Python pip
    yum: name=python-pip

  - name: Install Mysql-python
    command: pip install mysql-python

  - name: Install git
    yum: name=git state=latest

  - name: Cloning from git config files
    command: /usr/bin/git clone https://github.com/lotrikys/managed_ansible.git chdir=/usr/local/src/

  - name: Install configs for Apache and Nginx
    command: ./install.sh chdir=/usr/local/src/managed_ansible

  - name: Creating file /root/.my.cnf
    file: path=/root/.my.cnf state=touch
  - name: Fill file .my.cnf
    copy: content="[client]\nuser=root\npassword={{ mysql_root_password }}" dest=/root/.my.cnf

  - name: Adding user candidatest
    user: name=candidatest shell=/bin/bash

  - name: Change mode of /home/candidatest to 755
    file: path=/home/candidatest mode=0755

  - name: Adding folder 50.candidatest.top
    command: /usr/bin/mkdir -p /home/candidatest/50.candidatest.top/www

  - name: Starting Proftpd and adding to autorun
    service: name=proftpd state=started enabled=yes

  - name: Starting Apache and adding to autorun
    service: name=httpd state=started enabled=yes

  - name: Starting Nginx and adding to autorun
    service: name=nginx state=started enabled=yes

  - name: Starting MariaDB Server and adding to autorun
    service: name=mariadb state=started enabled=yes

  - name: Change root user password on first run
    mysql_user: login_user=root
        login_password=''
        name=root
        password={{ mysql_root_password }}
        priv=*.*:ALL,GRANT
        host={{ item }}
    with_items:
    - 127.0.0.1
    - localhost

  - name: Create database candidatest_wp
    mysql_db: name=candidatest_wp state=present
  - name: Create user for candidatest_wp
    mysql_user: name=candidatest_wp password=nZ4GhCoSEtEW6Y5PX priv=candidatest_wp.*:ALL state=present host={{ item }}
    with_items:
    - 127.0.0.1
    - localhost
    - 10.1.0.2

  - name: Create file info_about_php.php
    file: path=/home/candidatest/50.candidatest.top/www/info_about_php.php state=touch
  - name: Fill file info_about_php.php
    copy: content="<?php\nphpinfo();\n?>" dest=/home/candidatest/50.candidatest.top/www/info_about_php.php

  - name: Allow ftp from 10.1.0.0/24
    lineinfile: dest=/etc/hosts.allow line="{{ line_for_ftp }}"

  - name: Disabling SElinux
    lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=disabled

